### PR TITLE
fix: improve servux info line

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Comment by s-yh-china** [comment]
请暂时不要给还没做完的i18n增加工作量了

**Comment by zly2006** [comment]
> 请暂时不要给还没做完的i18n增加工作量了

OK, @sakura-ryoko please merge this after the i18n PR finishes.

**Comment by sakura-ryoko** [comment]
How did I miss this one ?

**Comment by s-yh-china** [comment]
zly2006 account was previously closed by GitHub, so this pr disappeared

**Comment by sakura-ryoko** [comment]
Hmm ....  I think this isn't a bad idea, but I think this PR might be a bit behind the i18n Line item.

**Comment by sakura-ryoko** [comment]
@zly2006 -- if you can update the code in this PR so it could be merged.  I am currently working on Snapshot quite heavily.

**Pull request closed without merging**
